### ISSUE TITLE
Update for Sequoia

### ISSUE THREAD

**Issue by zeekisthename** [GeantW0rld/hp-elitebook-840-g3-hackintosh#1]
Am using your EFI (modified) for HP laptop 250 G5.  Can boot Catalina through Sonoma 14.6 beta.

Have Skylake CPU and 520 graphics spoofed to Kabylake for Sonoma.  Have to use kernel args cpus=1 in order to boot.

However, Sequoia through beta 3 can boot only to login screen, enter password, and fails to progress to desktop.   Same issue with clean install or upgrade/install.

Request:

Do you have a working EFI for Sequoia?

Thank you.

**Comment by GeantW0rld** [comment]
hello, @zeekisthename,
I'm working on the EFI when Sequoia released
I'll reply you when the efi will out
