### ISSUE TITLE
Your config.plist booting DP4 to desktop

### ISSUE THREAD

**Issue by zeekisthename** [GeantW0rld/hp-elitebook-840-g3-hackintosh#2]
Apparently the Sequoia boot hang after login issue was resolved with DP4.

DP4 hung after login at analyitics window, but reboot took it to the desktop.

I believe there were only minor modifications necessary to your 840G3 Open Core config.plist in order to boot my hardware.

If you would like, can send you the config.plist.

It might save yoiu some time.

Additionally, with Sequoia the following kext should be upgraded if you are not running it already:

	<string>VoodooInput</string>
	<key>CFBundlePackageType</key>
	<string>KEXT</string>
	<key>CFBundleShortVersionString</key>
	<string>1.1.5</string>

Thank you.

**Comment by GeantW0rld** [comment]
hello,
Can I get your hardware specs?

**Comment by zeekisthename** [comment]
HP 250 G5 Intel Skylake GT2 HD Graphics 520, intel wifi, Intel Corporation Sunrise Point-LP, Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor Host Bridge

Sent with [Proton Mail](https://proton.me/) secure email.
